### ISSUE TITLE
PSD calculated on MFCC

### ISSUE THREAD

**Issue by arracso** [Sciss/SpeechRecognitionHMM#3]
I think you're calculating the powerSpectrum wrong on the MFCC.

The power spectrum is calculated by multiplying all components of the ftt by its conjugates.

So if some of the components is for example:
a + bi
then the PSD for this component is calculated as follows:
(a +  bi) * (a - bi) = a^2 - (bi)^2 = a^2 - b^2 * i^2 = a^2 + b^2

But for soem reason you are obtaining the sqrt of this. Is this right?? or is an error??

**Comment by Sciss** [comment]
Thank you for reporting. I am not actively working on this project (nor am I the original author of the code).
Notwithstanding, I do not believe this to be an issue. Since the MFCC are calculated based on the log of the mel-scale-filtered bands, the squaring would introduce simply a linear factor of two. (Of course, it also slightly changes the mel-scale accumulation, which I guess are supposed to be conserving the overall energy…). The effect on for example feature correlation is probably low. There are much more issues with the code base, for example `doCepstralMeanNormalization` is essentially a no-nop, as results are not stored.

**Comment by Sciss** [comment]
you might want to raise that issue here: https://github.com/gtiwari333/speech-recognition-java-hidden-markov-model-vq-mfcc
